// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: GpsLabel

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Switch1 = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_Switch1, 50);
lv_obj_set_height( ui_Switch1, 25);
lv_obj_set_x( ui_Switch1, -77 );
lv_obj_set_y( ui_Switch1, -132 );
lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );


ui_Switch2 = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_Switch2, 50);
lv_obj_set_height( ui_Switch2, 25);
lv_obj_set_x( ui_Switch2, -75 );
lv_obj_set_y( ui_Switch2, -96 );
lv_obj_set_align( ui_Switch2, LV_ALIGN_CENTER );


ui_Switch3 = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_Switch3, 50);
lv_obj_set_height( ui_Switch3, 25);
lv_obj_set_x( ui_Switch3, -72 );
lv_obj_set_y( ui_Switch3, -62 );
lv_obj_set_align( ui_Switch3, LV_ALIGN_CENTER );


ui_Switch4 = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_Switch4, 50);
lv_obj_set_height( ui_Switch4, 25);
lv_obj_set_x( ui_Switch4, -72 );
lv_obj_set_y( ui_Switch4, -27 );
lv_obj_set_align( ui_Switch4, LV_ALIGN_CENTER );


ui_Spinbox1 = lv_spinbox_create(ui_Screen1);
lv_obj_set_width( ui_Spinbox1, 70);
lv_obj_set_height( ui_Spinbox1, 42);
lv_obj_set_x( ui_Spinbox1, 65 );
lv_obj_set_y( ui_Spinbox1, -119 );
lv_obj_set_align( ui_Spinbox1, LV_ALIGN_CENTER );
lv_spinbox_set_digit_format( ui_Spinbox1, 4, 2);
lv_spinbox_set_range( ui_Spinbox1, 0,9999 );
lv_spinbox_set_step( ui_Spinbox1, round(pow(10, 1 - 1)) );

ui_Slider1 = lv_slider_create(ui_Screen1);
lv_obj_set_width( ui_Slider1, 150);
lv_obj_set_height( ui_Slider1, 10);
lv_obj_set_align( ui_Slider1, LV_ALIGN_CENTER );


ui_Checkbox1 = lv_checkbox_create(ui_Screen1);
lv_obj_set_width( ui_Checkbox1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox1, -44 );
lv_obj_set_y( ui_Checkbox1, 34 );
lv_obj_set_align( ui_Checkbox1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Checkbox2 = lv_checkbox_create(ui_Screen1);
lv_obj_set_width( ui_Checkbox2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox2, -42 );
lv_obj_set_y( ui_Checkbox2, 68 );
lv_obj_set_align( ui_Checkbox2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags


}
